Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  
  config.vm.network "forwarded_port", guest: 80, host: 8090
  config.vm.network "forwarded_port", guest: 5432, host: 5431
  
  config.vm.network "private_network", ip: "192.168.33.10"
  
  config.vm.synced_folder "../app", "/var/www/app", type: "virtualbox"
  config.vm.synced_folder "../db", "/var/lib/postgresql/db", type: "virtualbox"
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  
  config.vm.provision "shell", path: "bootstrap.sh"
end
