#! /bin/sh
### BEGIN INIT INFO
# Provides:          mailhog
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Mailhog
# Description:       Start Mailhog on boot.
### END INIT INFO

# Author: Camilo Carromeu <camilo@carromeu.com>
# Based on instructions by Bertrand Mathieu and template by Dan MacKinlay
# http://zebert.blogspot.com/2009/05/installing-django-solr-varnish-and.html
# https://gist.github.com/howthebodyworks/176149

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Start Mailhog"
NAME=mailhog
DAEMON=/usr/local/bin/mailhog.sh
DAEMON_ARGS=""
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

do_start()
{
	/usr/bin/env /usr/local/bin/mailhog > /dev/null 2>&1 &
	return 0
}

do_stop()
{
	return 0
}

do_reload() 
{
	return 0
}

case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  reload|force-reload)
	do_reload
	;;
  restart|force-reload)
	do_stop
	do_start
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
	exit 3
	;;
esac

:
